[listen]
host = '127.0.0.1' # httpf listener host
port = 8001        # httpf listener port

[resolve]
host = 'example.com' # protected resource that valid requests resolve to
port = 80            # port of host to connect to

[firewall]
trust_proxy_headers = false # useful if httpf is behind another proxy
trusted_headers = ['cf-connecting-ip', 'x-real-ip'] # only allow headers u trust

# permanant and cached blacklist/whitelist entries
blacklist = []
whitelist = ['127.0.0.1']

# database filepath
database = 'httpf.db'

# nginx style matchers (https://www.digitalocean.com/community/tutorials/nginx-location-directive)
# for denying/allowing access per ip
[[controls]]
path  = '/api'
allow = ['127.0.0.1']
deny  = ['all']
